---
  - name: 'Import GPG-KEY-elasticsearch'
    rpm_key:
      state: present
      key: https://packages.elastic.co/GPG-KEY-elasticsearch
  
  - name: 'Copy file for FILEBEAT repo'
    template:
      src: files/elastic.repo
      dest: "{{ filebeat_repo_path }}"

  - name: 'Install FILEBEAT'
    yum:
      name: filebeat
      state: present

  - name: 'Create FILEBEAT config file from template'
    template:
      src: templates/filebeat.yml.j2
      dest: /etc/filebeat/filebeat.yml
    notify:
      - restart filebeat