---
  - name: 'Install REPO zabbix server'
    yum:
      name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-2.el7.noarch.rpm
      state: present

  - name: 'Install zabbix server, web, zabbix agent'
    yum:
      name:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
    notify:
      - restart zabbix-server
      - restart zabbix-agent
      - restart httpd

  - name: 'Create ZABBIX config file from template'
    template:
      src: templates/zabbix_server.conf.j2
      dest: /etc/zabbix/zabbix_server.conf
    notify:
      - restart zabbix-server
  
  - name: 'ZABBIX config httpd date.timezone'
    template:
      src: templates/zabbix.conf.j2
      dest: /etc/httpd/conf.d/zabbix.conf
    notify:
      - restart httpd