---
# handlers file for nginx
#  handlers:
    - name: restart zabbix-server
      systemd:
        daemon_reload: yes
        name: zabbix-server
        state: restarted
        enabled: yes

    - name: reload zabbix-server
      systemd:
        name: zabbix-server
        state: reloaded

    - name: restart zabbix-agent
      systemd:
        daemon_reload: yes
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: reload zabbix-agent
      systemd:
        name: zabbix-agent
        state: reloaded

    - name: restart httpd
      systemd:
        daemon_reload: yes
        name: httpd
        state: restarted
        enabled: yes