---
    - name: restart zabbix-agent
      systemd:
        daemon_reload: yes
        name: zabbix-agent
        state: restarted
        enabled: yes

    - name: reload zabbix-agent
      systemd:
        name: zabbix-agent
        state: reloaded