---
  - name: 'Copy file for MariaDB repo'
    template:
      src: files/mariadb.repo
      dest: "{{ mariadb_repo_path }}"

  - name: 'Install MariaDB'
    yum:
      name:
        - epel-release
        - MariaDB-server
        - MariaDB-client
      state: present
  
  - name: Enable mariadb
    systemd:
      state: started
      name: mariadb
      enabled: yes

  - name: 'Create ZABBIX config file from template'
    template:
      src: templates/server.cnf.j2
      dest: /etc/my.cnf.d/server.cnf
  
  - name: Restart mariadb
    systemd:
      state: restarted
      name: mariadb