---
# tasks file for nginx
#- hosts: nginx
#  become: true

#  tasks:

  - name: 'Copy file for MariaDB repo'
    template:
      src: files/mariadb.repo
      dest: "{{ mariadb_repo_path }}"

  - name: 'Install MariaDB'
    yum:
      name:
        - epel-release
        - MariaDB-server
        - MariaDB-client
      state: present
    notify:
      - restart mariadb
  
  - name: 'Copy file create db and user'
    template:
      src: files/create_db_and_user.sh
      dest: /root/

  - name: 'Create DB and USER'
    shell: /root/create_db_and_user.sh
    
#  - name: 'Copy index.html'
#    template:
#      src: templates/index.html.j2
#      dest: /usr/share/nginx/html/index.html