---
  - name: 'Install PHP'
    yum:
      name: nginx
      state: present
    notify:
      - restart nginx

  - name: 'Create NGINX config file from template'
    template:
      src: templates/default.conf.j2
      dest: /etc/nginx/conf.d/default.conf
    notify:
      - reload nginx
    
  - name: 'Copy index.html'
    template:
      src: templates/index.html.j2
      dest: /usr/share/nginx/html/index.html