---
# handlers file for nginx
#  handlers:
    - name: restart mariadb
      systemd:
        daemon_reload: yes
        name: mariadb
        state: started
        enabled: yes

    - name: reload mariadb
      systemd:
        name: mariadb
        state: reloaded