---
# handlers file for nginx
#  handlers:
    - name: restart nginx
      systemd:
        daemon_reload: yes
        name: nginx
        state: restarted
        enabled: yes

    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded